import { statsAssets } from "./stats-assets";
import type { StatsDataset } from "./stats-data";

export const yearDataset: StatsDataset = {
  rangeLabel: "2026年",
  previousLabel: "上一年",
  nextLabel: "下一年",
  metricAria: "今年統計摘要",
  metrics: [
    {
      id: "sessions",
      label: "今年訓練次數",
      value: "86",
      unit: "次",
      trend: "↑ 45%",
      icon: "dumbbell",
      iconSrc: statsAssets.metricDumbbell,
    },
    {
      id: "volume",
      label: "今年總訓練量",
      value: "112k",
      unit: "kg",
      trend: "↑ 32%",
      icon: "trophy",
      iconSrc: statsAssets.metricTrophy,
    },
    {
      id: "active-days",
      label: "今年活躍天數",
      value: "63",
      unit: "天",
      trend: "↑ 40%",
      icon: "calendar",
      iconSrc: statsAssets.metricCalendar,
    },
  ],
  streak: {
    title: "最長連續訓練",
    compactTitle: "最長連續",
    value: "21",
    unit: "天",
    caption: "歷史最佳",
    desktopCaption: "歷史最佳紀錄",
    iconSrc: statsAssets.metricTrophyWhite,
  },
  duration: {
    title: "每月訓練次數",
    suffix: "（次）",
    subtitle: "2026 年度",
    average: "6",
    averageUnit: "次均",
    desktopAverageUnit: "次/月均",
    maxValue: 12,
    aria: "2026 年度每月訓練次數",
    bars: [
      { label: "1", value: 5 },
      { label: "2", value: 7 },
      { label: "3", value: 8 },
      { label: "4", value: 6, active: true, desktopDisplayValue: "6次" },
      { label: "5", value: 1, hiddenValue: true, variant: "muted" },
      { label: "6", value: 1, hiddenValue: true, variant: "muted" },
      { label: "7", value: 1, hiddenValue: true, variant: "muted" },
      { label: "8", value: 1, hiddenValue: true, variant: "muted" },
      { label: "9", value: 1, hiddenValue: true, variant: "muted" },
      { label: "10", value: 1, hiddenValue: true, variant: "muted" },
      { label: "11", value: 1, hiddenValue: true, variant: "muted" },
      { label: "12", value: 1, hiddenValue: true, variant: "muted" },
    ],
  },
  muscle: {
    title: "年度肌群分佈",
    centerValue: "86次",
    centerLabel: "今年",
    gradient:
      "conic-gradient(#ff6b35 0 30%, #4ecdc4 30% 54%, #f08080 54% 74%, #45b7d1 74% 88%, #ffcc00 88% 94%, #e5e5ea 94% 100%)",
    variant: "summary",
    groups: [
      { label: "胸部", value: "30%", color: "#ff6b35" },
      { label: "背部", value: "24%", color: "#4ecdc4" },
      { label: "腿部", value: "20%", color: "#f08080" },
      { label: "肩部", value: "14%", color: "#45b7d1" },
      { label: "核心", value: "6%", color: "#ffcc00" },
      { label: "其他", value: "6%", color: "#e5e5ea" },
    ],
  },
  prRecords: [
    {
      title: "背部訓練",
      date: "2026 · 2月 28日 10:00",
      desktopDate: "2/28 10:00",
      weight: "140",
      status: "↑ 年度 PR",
      positive: true,
    },
    {
      title: "胸部訓練",
      date: "2026 · 3月 15日 07:30",
      desktopDate: "3/15 07:30",
      weight: "120",
      status: "↑ 年度 PR",
      positive: true,
    },
    {
      title: "核心訓練",
      date: "2026 · 4月 1日",
      desktopDate: "4/1 07:00",
      weight: "100",
      status: "↑ 年度 PR",
      positive: true,
    },
    {
      title: "胸部・肩部訓練",
      date: "2026 · 4月 3日 08:45",
      desktopDate: "4/3 08:45",
      weight: "85",
      status: "↑ 年度 PR",
      positive: true,
      desktopOnly: true,
    },
  ],
};
